/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from "@tanstack/react-start/server";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as authenticatedRouteRouteImport } from "./routes/(authenticated)/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as authenticatedDashboardRouteImport } from "./routes/(authenticated)/dashboard";
import { Route as authPagesLoginRouteImport } from "./routes/(auth-pages)/login";
import { ServerRoute as ApiAuthSplatServerRouteImport } from "./routes/api/auth/$";

const rootServerRouteImport = createServerRootRoute();

const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: "/(authenticated)",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const authenticatedDashboardRoute = authenticatedDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => authenticatedRouteRoute,
} as any);
const authPagesLoginRoute = authPagesLoginRouteImport.update({
  id: "/(auth-pages)/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootServerRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof authenticatedRouteRouteWithChildren;
  "/login": typeof authPagesLoginRoute;
  "/dashboard": typeof authenticatedDashboardRoute;
}
export interface FileRoutesByTo {
  "/": typeof authenticatedRouteRouteWithChildren;
  "/login": typeof authPagesLoginRoute;
  "/dashboard": typeof authenticatedDashboardRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/(authenticated)": typeof authenticatedRouteRouteWithChildren;
  "/(auth-pages)/login": typeof authPagesLoginRoute;
  "/(authenticated)/dashboard": typeof authenticatedDashboardRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/login" | "/dashboard";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/login" | "/dashboard";
  id:
    | "__root__"
    | "/"
    | "/(authenticated)"
    | "/(auth-pages)/login"
    | "/(authenticated)/dashboard";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren;
  authPagesLoginRoute: typeof authPagesLoginRoute;
}
export interface FileServerRoutesByFullPath {
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
}
export interface FileServerRoutesByTo {
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath;
  fullPaths: "/api/auth/$";
  fileServerRoutesByTo: FileServerRoutesByTo;
  to: "/api/auth/$";
  id: "__root__" | "/api/auth/$";
  fileServerRoutesById: FileServerRoutesById;
}
export interface RootServerRouteChildren {
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/(authenticated)": {
      id: "/(authenticated)";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof authenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(authenticated)/dashboard": {
      id: "/(authenticated)/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof authenticatedDashboardRouteImport;
      parentRoute: typeof authenticatedRouteRoute;
    };
    "/(auth-pages)/login": {
      id: "/(auth-pages)/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof authPagesLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}
declare module "@tanstack/react-start/server" {
  interface ServerFileRoutesByPath {
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedDashboardRoute: typeof authenticatedDashboardRoute;
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardRoute: authenticatedDashboardRoute,
};

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  authPagesLoginRoute: authPagesLoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
};
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>();
